version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://localhost/mydatabase
    command: npm start
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    command: npm start