version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://localhost/mydatabase
    command: npm start
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    command: npm start