version: '3'
services:
  database:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spotiflix
  backend:
    depends_on:
      - database
    build: ./backend
    ports:
      - 8080:8080
    command: npm start
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/spotiflix
      - JWT_SECRET=${JWT_SECRET}
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./frontend/src:/usr/src/app/src